# Generated by Django 5.2.3 on 2025-07-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
